In [61]:
import os
import cv2
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report

from sequential import Sequential
from conv2d import Conv2D
from pooling2d import Pooling2D
from flatten import Flatten
from dense import Dense

In [62]:
np.random.seed(13517013)

In [63]:
image_size = (100, 100)

In [64]:
def readImage(path):
    result = []
    images = os.listdir(path)
    print(images)
    for image in images:
        result.append(cv2.resize(cv2.imread(path + '/' + image, 1), image_size))
    return np.array(result)

In [65]:
cats = readImage("./cats")

['cat.0.jpg', 'cat.15.jpg', 'cat.17.jpg', 'cat.19.jpg', 'cat.2.jpg', 'cat.21.jpg', 'cat.23.jpg', 'cat.26.jpg', 'cat.36.jpg', 'cat.38.jpg', 'cat.40.jpg', 'cat.45.jpg', 'cat.48.jpg', 'cat.49.jpg', 'cat.50.jpg', 'cat.58.jpg', 'cat.60.jpg', 'cat.61.jpg', 'cat.71.jpg', 'cat.9.jpg']


In [66]:
dogs = readImage("./dogs")

['dog.0.jpg', 'dog.24.jpg', 'dog.25.jpg', 'dog.3.jpg', 'dog.30.jpg', 'dog.34.jpg', 'dog.36.jpg', 'dog.38.jpg', 'dog.4.jpg', 'dog.40.jpg', 'dog.42.jpg', 'dog.5.jpg', 'dog.50.jpg', 'dog.51.jpg', 'dog.58.jpg', 'dog.60.jpg', 'dog.61.jpg', 'dog.63.jpg', 'dog.8.jpg', 'dog.9.jpg']


In [67]:
xdata = np.concatenate((cats, dogs))
yData = np.array([0] * len(cats) + [1] * len(dogs))

x_train, x_test, y_train, y_test = train_test_split(
        xdata, yData, test_size=0.1, random_state=13517013)

print(xdata.shape)

(40, 100, 100, 3)


In [68]:
model = Sequential()

model.add(Conv2D(1, (2, 2), pad=1, stride=2, input_shape=(xdata.shape[1], xdata.shape[2], xdata.shape[3]), activation='relu'))
model.add(Pooling2D((2, 2), stride=1))
model.add(Conv2D(1, (2, 2), pad=1, stride=2, input_shape=(99, 99, xdata.shape[3]), activation='relu'))
model.add(Flatten())
model.add(Dense(8, activation='relu'))
model.add(Dense(4, activation='sigmoid'))
model.add(Dense(1, activation='sigmoid'))

In [69]:
pred = model.forward(x_train)
print(pred)

[[0.27695213]
 [0.62589949]
 [0.40623732]
 [0.40623731]
 [0.10931578]
 [0.27695213]
 [0.22385038]
 [0.41587835]
 [0.41587835]
 [0.22385034]
 [0.18706318]
 [0.20139186]
 [0.41587835]
 [0.13873733]
 [0.10931578]
 [0.200159  ]
 [0.62589949]
 [0.27695213]
 [0.16207052]
 [0.62589949]
 [0.35168324]
 [0.35168324]
 [0.62589949]
 [0.62589949]
 [0.27695213]
 [0.23084577]
 [0.41587835]
 [0.41587835]
 [0.40623732]
 [0.10931578]
 [0.41587835]
 [0.27695213]
 [0.41584302]
 [0.41587835]
 [0.27695213]
 [0.2094171 ]]


c:\Users\alexa\OneDrive\Documents\KULIAH_SMT_7\advanced machine learning\activation.py:5: RuntimeWarning: overflow encountered in exp
  return 1/(1+np.exp(-x))


In [70]:
print(classification_report(y_train, np.round(pred)))

              precision    recall  f1-score   support

           0       0.55      0.94      0.69        18
           1       0.80      0.22      0.35        18

    accuracy                           0.58        36
   macro avg       0.67      0.58      0.52        36
weighted avg       0.67      0.58      0.52        36



In [71]:
# Make labels from possibility values
def makeLabels(pred):
    result = []
    for each_pred in pred:
        if each_pred >= 0.5:
            result.append("dogs")
        else:
            result.append("cats")
    return np.array(result)

print("Predicted Array")
print(makeLabels(pred))
print("Actual Array")
print(makeLabels(y_train))

[0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 1 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0]
[1 1 0 1 1 1 1 0 0 1 0 0 0 0 0 1 1 0 1 1 0 0 0 1 1 0 0 0 0 0 1 1 1 1 0 1]
